config/routes.rb
Rails.application.routes.draw do

  #get 'static_pages/home'

  #get 'static_pages/index'

  #get 'static_pages/about'

  #get 'static_pages/contact'

resources :articles do
        resources :comments
end

  get 'user/profile'
  get 'users/profile'
  get 'users/profile'
  #get 'home/index'

  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/home',    to: 'static_pages#home'
  #get  '/login',   to: 'user/session/new'
  get '/welcome',   to: 'welcome#index'

  devise_for :users
  

    root 'welcome#index'


end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login


    def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
    end

    validate :validate_username

    def validate_username
        if User.where(email: username).exists?
            errors.add(:username, :invalid)
        end
    end

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!
    http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
    end

    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end

    def update
        @article = Article.find(params[:id])

        if @article.update(article_params)
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy

        redirect_to articles_path
    end

    private
        def article_params
            params.require(:article).permit(:title,:text)
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!
 http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    @comment.user = current_user

    redirect_to article_path(@article)

  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:body).merge!(user_id: current_user.id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!
    def index
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
#before_action :authenticate_user!, except: [:about, :contact]
  def home
  end

  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def login=(login)
        @login = login
    end

    def login
        @login || self.username || self.email
    end

	def profile
        @user = User.find(params[:id])
	end

    def show
        @user = User.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title)
        base_title = "Eric's Web Application"
        if page_title.empty?
            base_title
        else
            "#{base_title} | #{page_title}"
        end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div id = "block">

    <div id="b2"><h1>Listing Articles</h1></div>
    <div id="b3"></div>
</div>

<br>
<br>
<%= link_to 'New article', new_article_path %>
<div>
<hr>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>When</th>
    <th colspan="3"></th>
  </tr>

  <% @articles.each do |article| %>

    <tr>
      <td class="col-md-3"><%= article.title %></td>
      <td class="col-md-6"><%= article.text %></td>
      <td class="col-md-2"><%= time_ago_in_words(article.created_at) %> ago </td>
      <td class="col-md-2"><%= link_to 'Show', article_path(article) %></td>
      <% if current_user.admin? %><td class="col-md-1"><%= link_to 'Edit', edit_article_path(article) %></td>
      <td class="col-md-1"><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td><% end %>
    </tr>

  <% end %>
</table>
</div>
<hr>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<table class="table">
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Comment:</strong>
  <%= comment.body %><br><br>
Posted <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user ? (link_to comment.user.username) : :null %> <br>
</p>


<p>
  <% if current_user.admin? %><%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %><% end %>
</p>
<hr>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
  <%= f.label("Commenting as ") %><br>
<%= link_to current_user.username, nil %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1><br>
<%= link_to 'Articoli', controller: 'articles' %><br>
<br>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Ruby on Rails Application
    by <a href="">Eric Natavio Solis</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Ruby-R3", '/', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to "Home",   home_path %></li>
        <% else %>
            <li><%= link_to "Home", root_path %></li>
        <% end %>
        <li><%= link_to "Help",   help_path %></li>
            <% if user_signed_in? %>
                <p class="navbar-text"><span class="glyphicon glyphicon-user"></span> Logged in as <%= current_user.username %></p>
                <li><%= link_to "Logout",  destroy_user_session_path, :method => :delete%></li>
            <% else %>
                <li></span><%= link_to "Log in", new_user_session_path %></li>
            <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= csrf_meta_tags %>
        <%= render 'layouts/shim' %>
    </head>
    <body>
        <%= render 'layouts/header' %>
        <div class="container">
            <%= yield %>
            <%= render 'layouts/footer' %>
        </div>
    </body>
</html>

app/views/static_pages/about.html.erb
<h1>Non c'è niente da vedere</h1>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

<p>Telegram: @NoReason7</p>

app/views/static_pages/help.html.erb
<h1>Non ti posso aiutare</h1>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Ruby-R3</h1>

  <h2>
    This is the home page for the
    <a href="/">Ruby-R3</a>
    application.
  </h2>
  <ul>What's in there?
	<li><%= link_to "Articles!", articles_path %></li>
  </ul>
</div>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

app/views/users/profile.html.erb
<h1>Users#profile</h1>
<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
    </tr>
  <% end %>
</table>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<title>Eric's Rails Application</title>
<h1>Hello, welcome to my page!</h1>

<% if user_signed_in? %><p><a class="btn btn-lg btn-primary" href="/home" role="button">Continue</a>
  <% else %>
<p><a class="btn btn-lg btn-primary" href="/users/sign_up" role="button">Sign up!</a>
<% end %>